name: Python Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Installer Chrome et ses dépendances
      - name: Install Chrome & dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb \
            wget unzip libnss3 libxss1 libappindicator3-1 fonts-liberation \
            libasound2t64 libatk1.0-0 libcups2 libgtk-3-0 libx11-xcb1 \
            libxcomposite1 libxdamage1 libxrandr2 libpangocairo-1.0-0 \
            libxshmfence1

      - name: Run Tests with Xvfb
        run: |
          xvfb-run -a pytest -v --maxfail=1 --disable-warnings